### ISSUE TITLE
Migrate DataStax provider into pulumiverse

### ISSUE THREAD

**Issue by vavsab** [pulumiverse/.github#20]
Hi team. 

Folks from pulumi team advised me [here](https://github.com/pulumi/pulumi/issues/9727#issuecomment-1141881462) to consider migrating my [DataStax Astra](https://www.datastax.com/products/datastax-astra) provider into pulumiverse. It is possible to do? And what should I do for this?

[Link to the provider](https://github.com/mapped/pulumi-astra)

**Comment by ringods** [comment]
Hello @vavsab, we will gladly accept this provider within the community. You remain the main care taker of your provider, but we can share the maintenance burden over everyone who would like to contribute.

If you transfer the ownership to me (Github user: `ringods`), I will move it forward to this Pulumiverse organization.

**Comment by vavsab** [comment]
Hi @ringods. Glad that finally I found the right place for the package. My org does not want to grant access to non-org members. Is it possible to do a fork or just clone the repo?
I will archive the original repo after that and make the CI work again.

We have no issues, no other contributions there. You may just transfer code from `main` branch.

**Comment by vavsab** [comment]
Or as an alternative you make create an empty repo called `provider-astra` and give me write access to it.

**Comment by ringods** [comment]
@vavsab I think there is some misunderstanding about permissions or access to *your* Github organization. I do not need to be added to your Github organization. Someone with admin rights on your Github organization has to transfer the repository *out* of your Github organization and make me the new owner of that repository.

See this for more information: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

I still want to follow this procedure because any people still browsing to the old location on Github will be redirect to the new location at Pulumiverse. This is something which wouldn't be there by only cloning the code.

**Comment by vavsab** [comment]
@ringods nobody is using this repo except me. I created it several days ago. So it will not make any difference. Except that waiting for my org admin is longer.

**Comment by vavsab** [comment]
@ringods please finish the transfer. My org admin says that you need to accept it

**Comment by ringods** [comment]
@vavsab the transfer is completed and I granted you access to the repository again.

**Comment by vavsab** [comment]
Thanks @ringods
